### ISSUE TITLE
Review: InventoryPage and Schema

### ISSUE THREAD

**Issue by skimura1** [Runtime-Terrorz/HOME-Project#19]
For this review, we're going to review the InventoryPage and Schema.

**Review Branch** 
[review-19](https://github.com/Runtime-Terrorz/HOME-Project/tree/review-19)

**Files to be reviewed**

- [Inventory.jsx](https://github.com/Runtime-Terrorz/HOME-Project/blob/master/app/imports/ui/pages/Inventory.jsx)
- [InventoryCollection.js](https://github.com/Runtime-Terrorz/HOME-Project/blob/master/app/imports/api/inventory/InventoryCollection.js)

**Checklist**

- [Architecture](https://github.com/Runtime-Terrorz/HOME-Project/blob/master/checklists/architecture-checklist.md)
- [Design](https://github.com/Runtime-Terrorz/HOME-Project/blob/master/checklists/design-checklist.md)
- [Javascript and ESLint](https://github.com/Runtime-Terrorz/HOME-Project/blob/master/checklists/js-checklist.md)
- [Testing](https://github.com/Runtime-Terrorz/HOME-Project/blob/master/checklists/testing-checklist.md)
- [React](https://github.com/Runtime-Terrorz/HOME-Project/blob/master/checklists/react-checklist.md)

**Due Date**

12 pm, Tuesday, September 14th.

**Documentation**

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by ruizaj** [comment]
Inventory.jsx
- L23 JS-01 className should be topInventory, makes css changes easier
- UI-02 The layout doesn't really work on a mobile screen, will need to update dimensions.
- L94 DE-05 Replace Stuff with Inventory
- TA-01 Needs an isDisplayed() acceptance test. 

InventoryCollection.js
- TU-01 Needs unit testings for this collection.
- TI-01 Needs integration testing.

**Comment by skimura1** [comment]
Inventory.jsx

L9, L18: DE-05: Comment is not relevant
L86 DE-05: Change stuff to inventory
TA-01: There is no isDisplayed() acceptance test

InventoryCollection.js

L74, L78: JS-06: can use isNaN() or typeof() in order to check if it is a number instead of underscore
TU-01: No unit tests
L103: Remove empty line 103

**Comment by huimichael** [comment]
Inventory.jsx
- L68 - L74: Look to rename some display names for view, for better understanding
	- Medication => Inventory Category
	- Name => Medication Name
	- Should have => Expected
	- Storage Location => Location
- L86: Change stuff to inventory
- TA-01 Needs an isDisplayed() acceptance test.

InventoryCollection.js 
- TU-01: Need unit tests
- L108: Change /** comment to //

**Comment by acatarinaoaraujo** [comment]
Inventory.jsx

L11, 87, 100: ARCH-01: Change the name of the file from Inventory to ListInventory or Inventory Page.
L86, 94: DESIGN-05: Modify the comment.

InventoryCollection.js

L7: TEST-UNIT-01: Create unit tests for the Inventory collection.
L1: TEST-INTEGRATION-01: Create integration tests for each meteor method.

Discuss about the acceptance test which verifies that each new page that has been displayed successfully.

**Comment by JasonKaneshiro** [comment]
Inventory.jsx
- L44 - L50: Better drop down filters
- L68 - 74:  Add one more column that has the tags
- L86 DE-05: Change stuff to inventory

InventoryCollection.js
- TU-01: missing unit testing
- TI-01: missing integration testing

**Comment by micahima** [comment]
Inventory.jsx
- 	L86: DESIGN-05: replace Stuff with Inventory
- 	L94: DESIGN-05: replace Stuff with Inventory
- 	TEST-ACCEPTANCE-01: isDisplayed() tested needed

InventoryCollection.js
- 	L74, L78: JS-06: use of underscore function
- 	TEST-UNIT-01: collection is missing unit tests.
- 	TEST-INTEGRATION-01: meteor method is missing integration tests.
- 	L103: blank line

**Comment by tonylong1314520** [comment]
Inventory.jsx

- L36-61: Make buttons responsive when changing size of page
- L72 DE-05: Make storage location have set locations for better organization
- L86 DE-05: Change stuff to inventory

InventoryCollection.js
- TU01: Need unit test for collections
- TI01: Need integration testing

**Comment by tonylong1314520** [comment]
Inventory.jsx

-L36-61: Make buttons responsive when changing size of page
-L72 DE-05: Make storage location have set locations for better organization
-L86 DE-05: Change stuff to inventory

InventoryCollection.js

-TU01: Need unit test for collections
-TI01: Need integration testing

**Comment by darneii** [comment]
Inventory.jsx

- L86, 94 DE-05: Change Stuff to inventory

- L71: Quantity -> In-Stock

- Switch L70 and L71 for better organization?

InventoryCollection.js

- TU-01: Need unit testing for collection
- LTI-01: Need to create integration testing

No ESLint errors came up

**Comment by cammoore** [comment]
## Inventory.jsx

RE-09: Prefer functions over classes.

RE-06: Use const in withTracker.

## InventoryCollection.js

L26: Check the type of lot. Does it have to be a number?
L27: Should expiration be a Date? 

L104 - 117: Do we want a publication for all the Inventory?
